/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.70
 * Generated at: 2017-03-13 06:27:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class profile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1489381952756L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1489386335023L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Minimal an Admin Panel Category Flat Bootstrap Responsive Website Template | Profile :: w3layouts</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<meta name=\"keywords\" content=\"Minimal Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, \r\n");
      out.write("Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design\" />\r\n");
      out.write("<script type=\"application/x-javascript\"> addEventListener(\"load\", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>\r\n");
      out.write("<link href=\"css/bootstrap.min.css\" rel='stylesheet' type='text/css' />\r\n");
      out.write("<!--<link href=\"css/bootstrap.css\" rel='stylesheet' type='text/css' />-->\r\n");
      out.write("<!-- Custom Theme files -->\r\n");
      out.write("<link href=\"css/style.css\" rel='stylesheet' type='text/css' />\r\n");
      out.write("<link href=\"css/font-awesome.css\" rel=\"stylesheet\"> \r\n");
      out.write("<script src=\"js/jquery.min.js\"> </script>\r\n");
      out.write("<script src=\"js/bootstrap.min.js\"> </script>\r\n");
      out.write("  \r\n");
      out.write("<!-- Mainly scripts -->\r\n");
      out.write("<script src=\"js/jquery.metisMenu.js\"></script>\r\n");
      out.write("<script src=\"js/jquery.slimscroll.min.js\"></script>\r\n");
      out.write("<!-- Custom and plugin javascript -->\r\n");
      out.write("<link href=\"css/custom.css\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"js/custom.js\"></script>\r\n");
      out.write("<script src=\"js/screenfull.js\"></script>\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t$(function () {\r\n");
      out.write("\t\t\t$('#supported').text('Supported/allowed: ' + !!screenfull.enabled);\r\n");
      out.write("\r\n");
      out.write("\t\t\tif (!screenfull.enabled) {\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t$('#toggle').click(function () {\r\n");
      out.write("\t\t\t\tscreenfull.toggle($('#container')[0]);\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"wrapper\">\r\n");
      out.write("      <!----->\r\n");
      out.write("       \r\n");
      out.write("       <!-- Header Start -->\r\n");
      out.write("  <nav class=\"navbar-default navbar-static-top\" role=\"navigation\">\r\n");
      out.write("             <div class=\"navbar-header\">\r\n");
      out.write("                <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-collapse\">\r\n");
      out.write("                    <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                    <span class=\"icon-bar\"></span>\r\n");
      out.write("                </button>\r\n");
      out.write("               <h1> <a class=\"navbar-brand\" href=\"index.html\">Minimal</a></h1>         \r\n");
      out.write("\t\t\t   </div>\r\n");
      out.write("\t\t\t <div class=\" border-bottom\">\r\n");
      out.write("        \t<div class=\"full-left\">\r\n");
      out.write("        \t  <section class=\"full-top\">\r\n");
      out.write("\t\t\t\t<button id=\"toggle\"><i class=\"fa fa-arrows-alt\"></i></button>\t\r\n");
      out.write("\t\t\t</section>\r\n");
      out.write("\t\t\t<form class=\" navbar-left-right\">\r\n");
      out.write("              <input type=\"text\"  value=\"Search...\" onfocus=\"this.value = '';\" onblur=\"if (this.value == '') {this.value = 'Search...';}\">\r\n");
      out.write("              <input type=\"submit\" value=\"\" class=\"fa fa-search\">\r\n");
      out.write("            </form>\r\n");
      out.write("            <div class=\"clearfix\"> </div>\r\n");
      out.write("           </div>\r\n");
      out.write("     \r\n");
      out.write("       \r\n");
      out.write("            <!-- Brand and toggle get grouped for better mobile display -->\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t   <!-- Collect the nav links, forms, and other content for toggling -->\r\n");
      out.write("\t\t    <div class=\"drop-men\" >\r\n");
      out.write("\t\t        <ul class=\" nav_1\">\r\n");
      out.write("\t\t           \r\n");
      out.write("\t\t    \t\t<li class=\"dropdown at-drop\">\r\n");
      out.write("\t\t              <a href=\"#\" class=\"dropdown-toggle dropdown-at \" data-toggle=\"dropdown\"><i class=\"fa fa-globe\"></i> <span class=\"number\">5</span></a>\r\n");
      out.write("\t\t              <ul class=\"dropdown-menu menu1 \" role=\"menu\">\r\n");
      out.write("\t\t                <li><a href=\"#\">\r\n");
      out.write("\t\t               \r\n");
      out.write("\t\t                \t<div class=\"user-new\">\r\n");
      out.write("\t\t                \t<p>New user registered</p>\r\n");
      out.write("\t\t                \t<span>40 seconds ago</span>\r\n");
      out.write("\t\t                \t</div>\r\n");
      out.write("\t\t                \t<div class=\"user-new-left\">\r\n");
      out.write("\t\t                \r\n");
      out.write("\t\t                \t<i class=\"fa fa-user-plus\"></i>\r\n");
      out.write("\t\t                \t</div>\r\n");
      out.write("\t\t                \t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t                \t</a></li>\r\n");
      out.write("\t\t                <li><a href=\"#\">\r\n");
      out.write("\t\t                \t<div class=\"user-new\">\r\n");
      out.write("\t\t                \t<p>Someone special liked this</p>\r\n");
      out.write("\t\t                \t<span>3 minutes ago</span>\r\n");
      out.write("\t\t                \t</div>\r\n");
      out.write("\t\t                \t<div class=\"user-new-left\">\r\n");
      out.write("\t\t                \r\n");
      out.write("\t\t                \t<i class=\"fa fa-heart\"></i>\r\n");
      out.write("\t\t                \t</div>\r\n");
      out.write("\t\t                \t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t                </a></li>\r\n");
      out.write("\t\t                <li><a href=\"#\">\r\n");
      out.write("\t\t                \t<div class=\"user-new\">\r\n");
      out.write("\t\t                \t<p>John cancelled the event</p>\r\n");
      out.write("\t\t                \t<span>4 hours ago</span>\r\n");
      out.write("\t\t                \t</div>\r\n");
      out.write("\t\t                \t<div class=\"user-new-left\">\r\n");
      out.write("\t\t                \r\n");
      out.write("\t\t                \t<i class=\"fa fa-times\"></i>\r\n");
      out.write("\t\t                \t</div>\r\n");
      out.write("\t\t                \t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t                </a></li>\r\n");
      out.write("\t\t                <li><a href=\"#\">\r\n");
      out.write("\t\t                \t<div class=\"user-new\">\r\n");
      out.write("\t\t                \t<p>The server is status is stable</p>\r\n");
      out.write("\t\t                \t<span>yesterday at 08:30am</span>\r\n");
      out.write("\t\t                \t</div>\r\n");
      out.write("\t\t                \t<div class=\"user-new-left\">\r\n");
      out.write("\t\t                \r\n");
      out.write("\t\t                \t<i class=\"fa fa-info\"></i>\r\n");
      out.write("\t\t                \t</div>\r\n");
      out.write("\t\t                \t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t                </a></li>\r\n");
      out.write("\t\t                <li><a href=\"#\">\r\n");
      out.write("\t\t                \t<div class=\"user-new\">\r\n");
      out.write("\t\t                \t<p>New comments waiting approval</p>\r\n");
      out.write("\t\t                \t<span>Last Week</span>\r\n");
      out.write("\t\t                \t</div>\r\n");
      out.write("\t\t                \t<div class=\"user-new-left\">\r\n");
      out.write("\t\t                \r\n");
      out.write("\t\t                \t<i class=\"fa fa-rss\"></i>\r\n");
      out.write("\t\t                \t</div>\r\n");
      out.write("\t\t                \t<div class=\"clearfix\"> </div>\r\n");
      out.write("\t\t                </a></li>\r\n");
      out.write("\t\t                <li><a href=\"#\" class=\"view\">View all messages</a></li>\r\n");
      out.write("\t\t              </ul>\r\n");
      out.write("\t\t            </li>\r\n");
      out.write("\t\t\t\t\t<li class=\"dropdown\">\r\n");
      out.write("\t\t              <a href=\"#\" class=\"dropdown-toggle dropdown-at\" data-toggle=\"dropdown\"><span class=\" name-caret\">Rackham<i class=\"caret\"></i></span><img src=\"images/wo.jpg\"></a>\r\n");
      out.write("\t\t              <ul class=\"dropdown-menu \" role=\"menu\">\r\n");
      out.write("\t\t                <li><a href=\"profile.jsp\"><i class=\"fa fa-user\"></i>Edit Profile</a></li>\r\n");
      out.write("\t\t                <li><a href=\"inbox.jsp\"><i class=\"fa fa-envelope\"></i>Inbox</a></li>\r\n");
      out.write("\t\t                <li><a href=\"calendar.jsp\"><i class=\"fa fa-calendar\"></i>Calender</a></li>\r\n");
      out.write("\t\t                <li><a href=\"inbox.jsp\"><i class=\"fa fa-clipboard\"></i>Tasks</a></li>\r\n");
      out.write("\t\t              </ul>\r\n");
      out.write("\t\t            </li>\r\n");
      out.write("\t\t           \r\n");
      out.write("\t\t        </ul>\r\n");
      out.write("\t\t     </div><!-- /.navbar-collapse -->\r\n");
      out.write("\t\t\t<div class=\"clearfix\">\r\n");
      out.write("       \r\n");
      out.write("     </div>\r\n");
      out.write("\t  \r\n");
      out.write("\t\t    <div class=\"navbar-default sidebar\" role=\"navigation\">\r\n");
      out.write("                <div class=\"sidebar-nav navbar-collapse\">\r\n");
      out.write("                <ul class=\"nav\" id=\"side-menu\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"index.jsp\" class=\" hvr-bounce-to-right\"><i class=\"fa fa-dashboard nav_icon \"></i><span class=\"nav-label\">Dashboards</span> </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                   \r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\" class=\" hvr-bounce-to-right\"><i class=\"fa fa-indent nav_icon\"></i> <span class=\"nav-label\">Menu Levels</span><span class=\"fa arrow\"></span></a>\r\n");
      out.write("                        <ul class=\"nav nav-second-level\">\r\n");
      out.write("                            <li><a href=\"graphs.jsp\" class=\" hvr-bounce-to-right\"> <i class=\"fa fa-area-chart nav_icon\"></i>Graphs</a></li>\r\n");
      out.write("                            \r\n");
      out.write("                            <li><a href=\"maps.jsp\" class=\" hvr-bounce-to-right\"><i class=\"fa fa-map-marker nav_icon\"></i>Maps</a></li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"typography.jsp\" class=\" hvr-bounce-to-right\"><i class=\"fa fa-file-text-o nav_icon\"></i>Typography</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t   </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("\t\t\t\t\t <li>\r\n");
      out.write("                        <a href=\"inbox.jsp\" class=\" hvr-bounce-to-right\"><i class=\"fa fa-inbox nav_icon\"></i> <span class=\"nav-label\">Inbox</span> </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    \r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"gallery.jsp\" class=\" hvr-bounce-to-right\"><i class=\"fa fa-picture-o nav_icon\"></i> <span class=\"nav-label\">Gallery</span> </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                     <li>\r\n");
      out.write("                        <a href=\"#\" class=\" hvr-bounce-to-right\"><i class=\"fa fa-desktop nav_icon\"></i> <span class=\"nav-label\">Pages</span><span class=\"fa arrow\"></span></a>\r\n");
      out.write("                        <ul class=\"nav nav-second-level\">\r\n");
      out.write("                            <li><a href=\"404.jsp\" class=\" hvr-bounce-to-right\"> <i class=\"fa fa-info-circle nav_icon\"></i>Error 404</a></li>\r\n");
      out.write("                            <li><a href=\"faq.jsp\" class=\" hvr-bounce-to-right\"><i class=\"fa fa-question-circle nav_icon\"></i>FAQ</a></li>\r\n");
      out.write("                            <li><a href=\"blank.jsp\" class=\" hvr-bounce-to-right\"><i class=\"fa fa-file-o nav_icon\"></i>Blank</a></li>\r\n");
      out.write("                       </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                     <li>\r\n");
      out.write("                        <a href=\"layout.jsp\" class=\" hvr-bounce-to-right\"><i class=\"fa fa-th nav_icon\"></i> <span class=\"nav-label\">Grid Layouts</span> </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                   \r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\" class=\" hvr-bounce-to-right\"><i class=\"fa fa-list nav_icon\"></i> <span class=\"nav-label\">Forms</span><span class=\"fa arrow\"></span></a>\r\n");
      out.write("                        <ul class=\"nav nav-second-level\">\r\n");
      out.write("                            <li><a href=\"forms.jsp\" class=\" hvr-bounce-to-right\"><i class=\"fa fa-align-left nav_icon\"></i>Basic forms</a></li>\r\n");
      out.write("                            <li><a href=\"validation.jsp\" class=\" hvr-bounce-to-right\"><i class=\"fa fa-check-square-o nav_icon\"></i>Validation</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                   \r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"#\" class=\" hvr-bounce-to-right\"><i class=\"fa fa-cog nav_icon\"></i> <span class=\"nav-label\">Settings</span><span class=\"fa arrow\"></span></a>\r\n");
      out.write("                        <ul class=\"nav nav-second-level\">\r\n");
      out.write("                            <li><a href=\"signin.jsp\" class=\" hvr-bounce-to-right\"><i class=\"fa fa-sign-in nav_icon\"></i>Signin</a></li>\r\n");
      out.write("                            <li><a href=\"signup.jsp\" class=\" hvr-bounce-to-right\"><i class=\"fa fa-sign-in nav_icon\"></i>Singup</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("        </nav>");
      out.write("\r\n");
      out.write("<!-- Header End  -->\r\n");
      out.write("       \r\n");
      out.write("\t\t <div id=\"page-wrapper\" class=\"gray-bg dashbard-1\">\r\n");
      out.write("       <div class=\"content-main\">\r\n");
      out.write(" \r\n");
      out.write(" \t<!--banner-->\t\r\n");
      out.write("\t\t    <div class=\"banner\">\r\n");
      out.write("\t\t    \t<h2>\r\n");
      out.write("\t\t\t\t<a href=\"index.html\">Home</a>\r\n");
      out.write("\t\t\t\t<i class=\"fa fa-angle-right\"></i>\r\n");
      out.write("\t\t\t\t<span>Profile</span>\r\n");
      out.write("\t\t\t\t</h2>\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t<!--//banner-->\r\n");
      out.write(" \t <!--gallery-->\r\n");
      out.write(" \t <div class=\" profile\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"profile-bottom\">\r\n");
      out.write("\t\t\t<h3><i class=\"fa fa-user\"></i>Profile</h3>\r\n");
      out.write("\t\t\t<div class=\"profile-bottom-top\">\r\n");
      out.write("\t\t\t<div class=\"col-md-4 profile-bottom-img\">\r\n");
      out.write("\t\t\t\t<img src=\"images/pr.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-8 profile-text\">\r\n");
      out.write("\t\t\t\t<h6>Jack Dorsey</h6>\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tr><td>Department</td>  \r\n");
      out.write("\t\t\t\t<td>:</td>  \r\n");
      out.write("\t\t\t\t<td>Web Designer</td></tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Email</td>\r\n");
      out.write("\t\t\t\t<td> :</td>\r\n");
      out.write("\t\t\t\t<td><a href=\"info@gmail.com\">info@lorem.com</a></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Skills</td>\r\n");
      out.write("\t\t\t\t<td> :</td>\r\n");
      out.write("\t\t\t\t<td> HTML, CSS,Jqury, Bootstrap</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>Country </td>\r\n");
      out.write("\t\t\t\t<td>:</td>\r\n");
      out.write("\t\t\t\t<td> United Arab Emirates</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"profile-bottom-bottom\">\r\n");
      out.write("\t\t\t<div class=\"col-md-4 profile-fo\">\r\n");
      out.write("\t\t\t\t<h4>23,5k</h4>\r\n");
      out.write("\t\t\t\t<p>Followers</p>\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"pro\"><i class=\"fa fa-plus-circle\"></i>Follow</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-4 profile-fo\">\r\n");
      out.write("\t\t\t\t<h4>348</h4>\r\n");
      out.write("\t\t\t\t<p>Following</p>\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"pro1\"><i class=\"fa fa-user\"></i>View Profile</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-md-4 profile-fo\">\r\n");
      out.write("\t\t\t\t<h4>23,5k</h4>\r\n");
      out.write("\t\t\t\t<p>Snippets</p>\r\n");
      out.write("\t\t\t\t<a href=\"#\"><i class=\"fa fa-cog\"></i>Options</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"profile-btn\">\r\n");
      out.write("\r\n");
      out.write("                <button type=\"button\" href=\"#\" class=\"btn bg-red\">Save changes</button>\r\n");
      out.write("           <div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--//gallery-->\r\n");
      out.write("\t\t<!---->\r\n");
      out.write("\r\n");
      out.write("<!-- Footer Start -->\r\n");
      out.write("<div class=\"copy\">\r\n");
      out.write("            <p> &copy; 2016 Minimal. All Rights Reserved | Design by <a href=\"http://w3layouts.com/\" target=\"_blank\">W3layouts</a> </p>\r\n");
      out.write("\t    </div>");
      out.write("\r\n");
      out.write("<!-- Footer End  -->\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"clearfix\"> </div>\r\n");
      out.write("       </div>\r\n");
      out.write("     \r\n");
      out.write("<!---->\r\n");
      out.write("\r\n");
      out.write("<!--scrolling js-->\r\n");
      out.write("\t<script src=\"js/jquery.nicescroll.js\"></script>\r\n");
      out.write("\t<script src=\"js/scripts.js\"></script>\r\n");
      out.write("\t<!--//scrolling js-->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
