/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.70
 * Generated at: 2017-01-12 15:39:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ProjectMangerHome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/CommonFile/alldatalinkofProjectmanger.jsp", Long.valueOf(1482656662968L));
    _jspx_dependants.put("/CommonFile/projectHomecommonfile.jsp", Long.valueOf(1484235521436L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write(" <style>\r\n");
      out.write("        .shape {\r\n");
      out.write("            border-style: solid;\r\n");
      out.write("            border-width: 0 70px 40px 0;\r\n");
      out.write("            float: right;\r\n");
      out.write("            height: 0px;\r\n");
      out.write("            width: 0px;\r\n");
      out.write("            -ms-transform: rotate(360deg);\r\n");
      out.write("            /* IE 9 */\r\n");
      out.write("            -o-transform: rotate(360deg);\r\n");
      out.write("            /* Opera 10.5 */\r\n");
      out.write("            -webkit-transform: rotate(360deg);\r\n");
      out.write("            /* Safari and Chrome */\r\n");
      out.write("            transform: rotate(360deg);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .offer {\r\n");
      out.write("            background: #fff;\r\n");
      out.write("            border: 1px solid #ddd;\r\n");
      out.write("            box-shadow: 0 10px 20px rgba(0, 0, 0, 0.2);\r\n");
      out.write("            margin: 15px 0;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .offer-radius {\r\n");
      out.write("            border-radius: 7px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .offer-danger {\r\n");
      out.write("            border-color: #d9534f;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .offer-danger .shape {\r\n");
      out.write("            border-color: transparent #d9534f transparent transparent;\r\n");
      out.write("            border-color: rgba(255, 255, 255, 0) #d9534f rgba(255, 255, 255, 0) rgba(255, 255, 255, 0);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .offer-success {\r\n");
      out.write("            border-color: #5cb85c;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .offer-success .shape {\r\n");
      out.write("            border-color: transparent #5cb85c transparent transparent;\r\n");
      out.write("            border-color: rgba(255, 255, 255, 0) #5cb85c rgba(255, 255, 255, 0) rgba(255, 255, 255, 0);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .offer-default {\r\n");
      out.write("            border-color: #999999;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .offer-default .shape {\r\n");
      out.write("            border-color: transparent #999999 transparent transparent;\r\n");
      out.write("            border-color: rgba(255, 255, 255, 0) #999999 rgba(255, 255, 255, 0) rgba(255, 255, 255, 0);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .offer-primary {\r\n");
      out.write("            border-color: #428bca;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .offer-primary .shape {\r\n");
      out.write("            border-color: transparent #428bca transparent transparent;\r\n");
      out.write("            border-color: rgba(255, 255, 255, 0) #428bca rgba(255, 255, 255, 0) rgba(255, 255, 255, 0);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .offer-info {\r\n");
      out.write("            border-color: #5bc0de;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .offer-info .shape {\r\n");
      out.write("            border-color: transparent #5bc0de transparent transparent;\r\n");
      out.write("            border-color: rgba(255, 255, 255, 0) #5bc0de rgba(255, 255, 255, 0) rgba(255, 255, 255, 0);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .offer-warning {\r\n");
      out.write("            border-color: #f0ad4e;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .offer-warning .shape {\r\n");
      out.write("            border-color: transparent #f0ad4e transparent transparent;\r\n");
      out.write("            border-color: rgba(255, 255, 255, 0) #f0ad4e rgba(255, 255, 255, 0) rgba(255, 255, 255, 0);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .shape-text {\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            font-size: 12px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            right: -40px;\r\n");
      out.write("            top: 2px;\r\n");
      out.write("            white-space: nowrap;\r\n");
      out.write("            -ms-transform: rotate(30deg);\r\n");
      out.write("            /* IE 9 */\r\n");
      out.write("            -o-transform: rotate(360deg);\r\n");
      out.write("            /* Opera 10.5 */\r\n");
      out.write("            -webkit-transform: rotate(30deg);\r\n");
      out.write("            /* Safari and Chrome */\r\n");
      out.write("            transform: rotate(30deg);\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .offer-content {\r\n");
      out.write("            padding: 0 20px 10px;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write(" \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<h1>Project Manger Home</h1>\r\n");
      out.write("<nav class=\"navbar navbar-inverse\">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <div class=\"navbar-header\">\r\n");
      out.write("      <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#myNavbar\">\r\n");
      out.write("        <span class=\"icon-bar\"></span>\r\n");
      out.write("        <span class=\"icon-bar\"></span>\r\n");
      out.write("        <span class=\"icon-bar\"></span>                        \r\n");
      out.write("      </button>\r\n");
      out.write("      <a class=\"navbar-brand\" href=\"home.jsp\">Project Manger</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"myNavbar\">\r\n");
      out.write("      <ul class=\"nav navbar-nav\">\r\n");
      out.write("        <li class=\"active\"><a href=\"home.jsp\">Home</a></li>\r\n");
      out.write("        <li class=\"dropdown\">\r\n");
      out.write("         <a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">Intern <span class=\"caret\"></span></a>\r\n");
      out.write("           <ul class=\"dropdown-menu\">\r\n");
      out.write("            <li><a href=\"AllIntern.action\">See All Intern</a></li>\r\n");
      out.write("            <li><a href=\"RegisterIntern.jsp\">Register Intern</a></li>\r\n");
      out.write("             <li><a href=\"viewLeaveByProject.action\">Verify Intern Leave</a></li>\r\n");
      out.write("              <li><a href=\"projectmangerverifyInterview.action\">Verify Intern Interview</a></li>\r\n");
      out.write("           \r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("         <li class=\"dropdown\">\r\n");
      out.write("         <a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\">Batch <span class=\"caret\"></span></a>\r\n");
      out.write("           <ul class=\"dropdown-menu\">\r\n");
      out.write("            <li><a href=\"addbatch11.action\">Add Batch</a></li>\r\n");
      out.write("            <li><a href=\"seeAllBatch.action\">View All Batch</a></li>\r\n");
      out.write("            <li><a href=\"addGruop11.action\">Add Group</a></li>\r\n");
      out.write("            <li><a href=\"ViewAllGroup.action\">View All Group</a></li>\r\n");
      out.write("             <li><a href=\"assignProjectTaskByprojectManger.action\">Assign Project</a></li>\r\n");
      out.write("            <li><a href=\"ViewAssignTask.action\">View Assign Project</a></li>\r\n");
      out.write("           \t<li><a href=\"AddTaskOfPjt.action\"> Add Task Of Project</a></li>\r\n");
      out.write("           \t<li><a href=\"ViewTaskOfPjt.action\"> View Task Of Project</a></li>\r\n");
      out.write("           \t<li><a href=\"createExam.jsp\">Create Exam</a></li>\r\n");
      out.write(" \t\t\t<li><a href=\"ViewExam.action\">View Exam</a></li>\r\n");
      out.write(" \t\t\t<li><a href=\"viewAddedQuestion.action\">View Added Questions</a></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("        <!-- <li><a href=\"#\">list</a></li>\r\n");
      out.write("        <li><a href=\"#\">List</a></li> -->\r\n");
      out.write("      </ul>\r\n");
      out.write("      <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("        <li><a href=\"ProjectChangepwd.action?id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.pmInfo.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"><span class=\"glyphicon glyphicon-user\"></span> ChangePassword</a></li>\r\n");
      out.write("        <li><a href=\"logoutfrompage.action?id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.pmInfo.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"><span class=\"glyphicon glyphicon-log-in\"></span> Log Out</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</nav>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<div class=\"alert alert-info\">\r\n");
      out.write("    <h4><strong>Project Manger!</strong> Home.</h4>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("  ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.msg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("<!-- For Massage -->\r\n");
      out.write("<div class=\"container\">  \r\n");
      out.write(" <table class=\"table table-hover\">\r\n");
      out.write(" <thead>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>Id</th>\r\n");
      out.write("\t\t\t<th>First Name</th>\r\n");
      out.write("\t\t\t<th>Last Name</th>\r\n");
      out.write("\t\t\t<th>User Name</th>\r\n");
      out.write("\t\t\t<th>Email</th>\r\n");
      out.write("\t\t\t<th>Mobile No.</th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write(" </thead>\r\n");
      out.write("\t\t\r\n");
      out.write(" <tbody>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.pmInfo.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("<td>\r\n");
      out.write("\t\t<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.pmInfo.fname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("<td>\r\n");
      out.write("\t\t<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.pmInfo.lname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("<td>\r\n");
      out.write("\t\t<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.pmInfo.username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("<td>\r\n");
      out.write("\t\t<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.pmInfo.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("<td>\r\n");
      out.write("\t\t<td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.pmInfo.mob}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("<td>\r\n");
      out.write("\t\t<td><a href=\"editprojectmanger.action?id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.pmInfo.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" class=\"btn btn-success\">Edit Profile</a></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</tbody>\r\n");
      out.write("<!-- <button id=\"PageRefresh\">Refresh a Page in jQuery</button> -->\r\n");
      out.write("</table>");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("        <h1 class=\"thick-heading\">\r\n");
      out.write("        ||Alert Example||\r\n");
      out.write("      </h1>\r\n");
      out.write("\r\n");
      out.write("        <!-- First Featurette -->\r\n");
      out.write("        <div class=\"featurette\" id=\"about\">\r\n");
      out.write("            <!------------------------code---------------start---------------->\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-xs-3\">\r\n");
      out.write("                        <div class=\"offer offer-default\">\r\n");
      out.write("                            <div class=\"shape\">\r\n");
      out.write("                                <div class=\"shape-text\">\r\n");
      out.write("                                    Batch\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"offer-content\">\r\n");
      out.write("                                <h3 class=\"lead\">\r\n");
      out.write("\t\t\t\t\t\t\tA default offer\r\n");
      out.write("\t\t\t\t\t\t</h3>\r\n");
      out.write("                                <p>\r\n");
      out.write("                                    And a little description.\r\n");
      out.write("                                    <br> and so one\r\n");
      out.write("                                </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-xs-3\">\r\n");
      out.write("                        <div class=\"offer offer-success\">\r\n");
      out.write("                            <div class=\"shape\">\r\n");
      out.write("                                <div class=\"shape-text\">\r\n");
      out.write("                                    Batch\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"offer-content\">\r\n");
      out.write("                                <h3 class=\"lead\">\r\n");
      out.write("\t\t\t\t\t\t\tA success offer\r\n");
      out.write("\t\t\t\t\t\t</h3>\r\n");
      out.write("                                <p>\r\n");
      out.write("                                    And a little description.\r\n");
      out.write("                                    <br> and so one\r\n");
      out.write("                                </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-xs-3\">\r\n");
      out.write("                        <div class=\"offer offer-radius offer-primary\">\r\n");
      out.write("                            <div class=\"shape\">\r\n");
      out.write("                                <div class=\"shape-text\">\r\n");
      out.write("                                    Group\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"offer-content\">\r\n");
      out.write("                                <h3 class=\"lead\">\r\n");
      out.write("\t\t\t\t\t\t\tA primary-radius\r\n");
      out.write("\t\t\t\t\t\t</h3>\r\n");
      out.write("                                <p>\r\n");
      out.write("                                    And a little description.\r\n");
      out.write("                                    <br> and so one\r\n");
      out.write("                                </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-xs-3\">\r\n");
      out.write("                        <div class=\"offer offer-info\">\r\n");
      out.write("                            <div class=\"shape\">\r\n");
      out.write("                                <div class=\"shape-text\">\r\n");
      out.write("                                    Group\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"offer-content\">\r\n");
      out.write("                                <h3 class=\"lead\">\r\n");
      out.write("\t\t\t\t\t\t\tAn info offer\r\n");
      out.write("\t\t\t\t\t\t</h3>\r\n");
      out.write("                                <p>\r\n");
      out.write("                                    And a little description.\r\n");
      out.write("                                    <br> and so one\r\n");
      out.write("                                </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-xs-3\">\r\n");
      out.write("                        <div class=\"offer offer-warning\">\r\n");
      out.write("                            <div class=\"shape\">\r\n");
      out.write("                                <div class=\"shape-text\">\r\n");
      out.write("                                    Assign Project\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"offer-content\">\r\n");
      out.write("                                <h3 class=\"lead\">\r\n");
      out.write("\t\t\t\t\t\t\t Assign Project\r\n");
      out.write("\t\t\t\t\t\t</h3>\r\n");
      out.write("                                <p>\r\n");
      out.write("                                    And a little description.\r\n");
      out.write("                                    <br> and so one\r\n");
      out.write("                                </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-xs-3\">\r\n");
      out.write("                        <div class=\"offer offer-radius offer-danger\">\r\n");
      out.write("                            <div class=\"shape\">\r\n");
      out.write("                                <div class=\"shape-text\">\r\n");
      out.write("                                     Assign Project\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"offer-content\">\r\n");
      out.write("                                <h3 class=\"lead\">\r\n");
      out.write("\t\t\t\t\t\t\t View Assign\r\n");
      out.write("\t\t\t\t\t\t</h3>\r\n");
      out.write("                                <p>\r\n");
      out.write("                                    And a little description.\r\n");
      out.write("                                    <br> and so one\r\n");
      out.write("                                </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"col-xs-3\">\r\n");
      out.write("                        <div class=\"offer offer-radius offer-danger\">\r\n");
      out.write("                            <div class=\"shape\">\r\n");
      out.write("                                <div class=\"shape-text\">\r\n");
      out.write("                                      Project task\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"offer-content\">\r\n");
      out.write("                                <h3 class=\"lead\">\r\n");
      out.write("\t\t\t\t\t\t\t View Assign\r\n");
      out.write("\t\t\t\t\t\t</h3>\r\n");
      out.write("                                <p>\r\n");
      out.write("                                    And a little description.\r\n");
      out.write("                                    <br> and so one\r\n");
      out.write("                                </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"col-xs-3\">\r\n");
      out.write("                        <div class=\"offer offer-radius offer-danger\">\r\n");
      out.write("                            <div class=\"shape\">\r\n");
      out.write("                                <div class=\"shape-text\">\r\n");
      out.write("                                     Assign Project\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"offer-content\">\r\n");
      out.write("                                <h3 class=\"lead\">\r\n");
      out.write("\t\t\t\t\t\t\t View Assign\r\n");
      out.write("\t\t\t\t\t\t</h3>\r\n");
      out.write("                                <p>\r\n");
      out.write("                                    And a little description.\r\n");
      out.write("                                    <br> and so one\r\n");
      out.write("                                </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"col-xs-3\">\r\n");
      out.write("                        <div class=\"offer offer-radius offer-danger\">\r\n");
      out.write("                            <div class=\"shape\">\r\n");
      out.write("                                <div class=\"shape-text\">\r\n");
      out.write("                                     Exam\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"offer-content\">\r\n");
      out.write("                                <h3 class=\"lead\">\r\n");
      out.write("\t\t\t\t\t\t\t About Exam\r\n");
      out.write("\t\t\t\t\t\t</h3>\r\n");
      out.write("                                <p>\r\n");
      out.write("                                    And a little description.\r\n");
      out.write("                                    <br> and so one\r\n");
      out.write("                                </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"col-xs-3\">\r\n");
      out.write("                        <div class=\"offer offer-radius offer-danger\">\r\n");
      out.write("                            <div class=\"shape\">\r\n");
      out.write("                                <div class=\"shape-text\">\r\n");
      out.write("                                     View Exam\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"offer-content\">\r\n");
      out.write("                                <h3 class=\"lead\">\r\n");
      out.write("\t\t\t\t\t\t\t About Exam\r\n");
      out.write("\t\t\t\t\t\t</h3>\r\n");
      out.write("                                <p>\r\n");
      out.write("                                    And a little description.\r\n");
      out.write("                                    <br> and so one\r\n");
      out.write("                                </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!----Code------end----------------------------------->\r\n");
      out.write("        </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
