/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.70
 * Generated at: 2016-07-19 07:53:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Green Planet</title>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<link href=\"style.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<script src=\"js/jquery-1.3.2.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"js/cufon-yui.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"js/cufon-replace.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"js/cufon-replace.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"js/Bauhaus_Md_BT_400.font.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<!--[if lt IE 7]><link href=\"style_ie.css\" rel=\"stylesheet\" type=\"text/css\" /><![endif]-->\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body id=\"page1\">\r\n");
      out.write("<div id=\"main\">\r\n");
      out.write("  <!-- header -->\r\n");
      out.write("  <div id=\"header\">\r\n");
      out.write("    <ul class=\"site-nav\">\r\n");
      out.write("      <li><a href=\"index.html\" class=\"act\">Home</a></li>\r\n");
      out.write("      <li><a href=\"about-us.html\">About Us</a></li>\r\n");
      out.write("      <li><a href=\"articles.html\">Articles</a></li>\r\n");
      out.write("      <li><a href=\"contact-us.html\">Contact Us</a></li>\r\n");
      out.write("      <li><a href=\"sitemap.html\">Site Map</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("    <div class=\"logo\"><a href=\"#\"><img src=\"images/logo.gif\" alt=\"\" /></a></div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- content -->\r\n");
      out.write("  <div id=\"content\">\r\n");
      out.write("    <div class=\"indent1\">\r\n");
      out.write("      <div class=\"indent\">\r\n");
      out.write("        <h2>Welcome to Green Planet!</h2>\r\n");
      out.write("        <h3>Green Planet is a free websites template created by Templates.com team. This website template is optimized for 1024X768 screen resolution. It is also XHTML &amp; CSS valid.</h3>\r\n");
      out.write("        <p>The website template goes with two packages â with PSD source files and without them. PSD source files are available for free for the registered members of Templates.com. The basic package (without PSD is available for anyone without registration).</p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <h2>Recent Articles</h2>\r\n");
      out.write("      <ul class=\"list\">\r\n");
      out.write("        <li><a href=\"#\">Green Planet</a><br />\r\n");
      out.write("          From our site you will learn interesting facts about Green Planet and its inhabitants. Your journey starts here!</li>\r\n");
      out.write("        <li><a href=\"#\">Green Planet Template</a><br />\r\n");
      out.write("          Free 1028X768 Optimized Website Template from Templates.com! We really hope that you like this template and will use for your websites.</li>\r\n");
      out.write("        <li><a href=\"#\">Travel to the Green Planet</a><br />\r\n");
      out.write("          The captivating stories about the journey to the Green Planet you can read in this sample article.</li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- footer -->\r\n");
      out.write("  <div id=\"footer\">\r\n");
      out.write("    <div class=\"indent\">\r\n");
      out.write("      <div class=\"fleft\">Copyright - Type in Your Name</div>\r\n");
      out.write("      <div class=\"fright\">Designed by: <a href=\"http://www.templates.com\"><img alt=\"\" src=\"images/templates-logo.gif\" /></a>&nbsp; Your Provider of <a href=\"http://www.templates.com\">Website Templates</a></div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<script type=\"text/javascript\"> Cufon.now(); </script>\r\n");
      out.write("<div align=center>This template  downloaded form <a href='http://all-free-download.com/free-website-templates/'>free website templates</a></div></body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
