package org.spring.CustomerBeans;

public class ChangePwdBeans {

	private int custId;
	private String email;
	private String autogeneratedPwd;
	
	public int getCustId() {
		return custId;
	}

	public void setCustId(int custId) {
		this.custId = custId;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getAutogeneratedPwd() {
		return autogeneratedPwd;
	}

	public void setAutogeneratedPwd(String autogeneratedPwd) {
		this.autogeneratedPwd = autogeneratedPwd;
	}

}
