create table policy111"
				+ "("
				+ "policyId number(5) primary key,"
				+ "policyName varchar(50),"
				+ "typeofcoverage varchar(50),"
				+ "durations varchar(50)"
				+ ");
				
create table agentregister"
				+ "("
				+ "agentId number(5) primary key,"
				+ "agentName varchar(50),"
				+ "agentemail varchar(100),"
				+ "agentpassword varchar(50),"
				+ "agentcfpassword varchar(50),"
				+ "agentaddress varchar(255),"
				+ "agentgender varchar(50),"
				+ "agentpanNo varchar(10),"
				+ "agentdob date,"
				+ "agentmobNo varchar(15),"
				+ "agentstate varchar(50),"
				+ "agentpostcode varchar(10),"
				+ "agentcountry varchar(50)"
				+ ");
				
create table clientregister"
				+ "("
				+ "clientId number(5) primary key,"
				+ "clientName varchar(50),"
				+ "clientemail varchar(100),"
				+ "clientpassword varchar(50),"
				+ "clientcfpassword varchar(50),"
				+ "clientaddress varchar(255),"
				+ "clientgender varchar(50),"
				+ "clientpanNo varchar(10),"
				+ "clientdob date,"
				+ "clientmobNo varchar(15),"
				+ "clientstate varchar(50),"
				+ "clientpostcode varchar(10),"
				+ "clientoccuption varchar(50)"
				+ "clientincome varchar(50)"
				+ "clientcountry varchar(50)"
				+ ")";