create table admin123"
			+ "("
			+ "adminId number(9)primary key,"
			+ "username varchar2(50),"
			+ "password varchar2(50)"
			+ ");

create table policy111"
				+ "("
				+ "policyId number(5) primary key,"
				+ "policyName varchar(50),"
				+ "typeofcoverage varchar(50),"
				+ "durations varchar(50)"
				+ ");
				
create table agentregister"
				+ "("
				+ "agentId number(5) primary key,"
				+ "agentName varchar(50),"
				+ "agentemail varchar(100),"
				+ "agentpassword varchar(50),"
				+ "agentcfpassword varchar(50),"
				+ "agentaddress varchar(255),"
				+ "agentgender varchar(50),"
				+ "agentpanNo varchar(10),"
				+ "agentdob date,"
				+ "agentmobNo varchar(15),"
				+ "agentstate varchar(50),"
				+ "agentpostcode varchar(10),"
				+ "agentcountry varchar(50)"
				+ ");
				
create table clientregister"
				+ "("
				+ "clientId number(5) primary key,"
				+ "clientName varchar(50),"
				+ "clientemail varchar(100),"
				+ "clientpassword varchar(50),"
				+ "clientcfpassword varchar(50),"
				+ "clientaddress varchar(255),"
				+ "clientgender varchar(50),"
				+ "clientpanNo varchar(10),"
				+ "clientdob date,"
				+ "clientmobNo varchar(15),"
				+ "clientstate varchar(50),"
				+ "clientpostcode varchar(10),"
				+ "clientoccuption varchar(50)"
				+ "clientincome varchar(50)"
				+ "clientcountry varchar(50)"
				+ ");

create table clientspolicy"
			+ "("
			+ "policyNo number(9) primary key,"
			+ "policyDate varchar(50),"
			+ "policymaturityDate varchar(50),"
			+ "policysumInsured varchar(20),"
			+ "policypremiumAmount varchar(20),"
			+ "policycommission varchar(20),"
			+ "paymentmethod varchar(20),"
			+ "policyId number(9),"
			+ "FOREIGN KEY (policyId) REFERENCES policy111(policyId),"
			+ "agentId number(9),"
			+ "FOREIGN KEY (agentId) REFERENCES agentregister(agentId),"
			+ "clientId number(9),"
			+ "FOREIGN KEY (clientId) REFERENCES clientregister(clientId)"
			+ ");
			
create table vehicles"
			+ "("
			+ "vehicleId number(9) primary key,"
			+ "fromdate varchar(50),"
			+ "todate varchar(50),"
			+ "dateofregister varchar(50),"
			+ "manufacturedate varchar(50),"
			+ "registerno varchar(50),"
			+ "usedfuel varchar(50),"
			+ "engineNo varchar(50),"
			+ "cublic varchar(50),"
			+ "chassisNo varchar(30),"
			+ "make varchar(20),"
			+ "model varchar(20),"
			+ "idv varchar(25),"
			+ "thirdparty varchar(50),"
			+ "servicetax varchar(20),"
			+ "total varchar(20),"
			+ "paymentMethod varchar(50),"
			+ "agentId number(9),"
			+ "FOREIGN KEY (agentId) REFERENCES agentregister(agentId),"
			+ "clientId number(9),"
			+ "FOREIGN KEY (clientId) REFERENCES clientregister(clientId)"
			+ ");
			
create table enquirycustomers"
			+ "("
			+ "enquiryId number(9) primary key ,"
			+ "customerName varchar(50),"
			+ "customaddress varchar(255),"
			+ "customMobNo varchar(15),"
			+ "enquirydate varchar(50),"
			+ "policyId number(9),"
			+ "FOREIGN KEY (policyId) REFERENCES policy111(policyId),"
			+ "agentId number(9),"
			+ "FOREIGN KEY (agentId) REFERENCES agentregister(agentId)"
			+ ");
			
create table quotations"
			+ "("
			+ "quotationId number(9) primary key,"
			+ "quotationAmounts varchar(50),"
			+ "replydate varchar(50),"
			+ "enquiryId number(9),"
			+ "FOREIGN KEY (enquiryId) REFERENCES enquirycustomers(enquiryId),"
			+ "policyId number(9),"
			+ "FOREIGN KEY (policyId) REFERENCES policy111(policyId)"
			+ ");

create table health"
			+ "("
			+ "healthId number(9) primary key,"
			+ "healthfromdate varchar(50),"
			+ "healthtodate varchar(50),"
			+ "healthopt1 varchar(20),"
			+ "healthopt2 varchar(20),"
			+ "healthopt3 varchar(20),"
			+ "healthidv varchar(50),"
			+ "healththirdparty varchar(50),"
			+ "healthservicetax varchar(50),"
			+ "paymethod varchar(20),"
			+ "agentId number(9),"
			+ "FOREIGN KEY (agentId) REFERENCES agentregister(agentId),"
			+ "clientId number(9),"
			+ "FOREIGN KEY (clientId) REFERENCES clientregister(clientId)"
			+ ");
			
create table healthnominee"
			+ "("
			+ "healthNomineeId number(9) primary key,"
			+ "healthsumInsured varchar(20),"
			+ "healthpriemium varchar(20),"
			+ "healthnomineeName varchar(50),"
			+ "healthrelationsWithNominee varchar(50),"
			+ "policyId number(9),"
			+ "FOREIGN KEY (policyId) REFERENCES policy111(policyId),"
			+ "clientId number(9),"
			+ "FOREIGN KEY (clientId) REFERENCES clientregister(clientId)"
			+ ");
			
create table vehiclenominee"
			+ "("
			+ "healthNomineeId number(9) primary key,"
			+ "healthsumInsured varchar(20),"
			+ "healthpriemium varchar(20),"
			+ "healthnomineeName varchar(50),"
			+ "healthrelationsWithNominee varchar(50),"
			+ "policyId number(9),"
			+ "FOREIGN KEY (policyId) REFERENCES policy111(policyId),"
			+ "clientId number(9),"
			+ "FOREIGN KEY (clientId) REFERENCES clientregister(clientId)"
			+ ");