package org.spring.EmployeeBeans;

public class CustomersBeans {

	private int custId;
	private String from = "kkumawat1111@gmail.com";// from Admin Id
	private String email;// to customer Id
	private String custName;
	private String middleName;
	private String lastName;
	private String custMobNo;
	private String gender;
	private String custNationlity;
	private String custDob;
	private String custPincode;
	private String custCountry;
	private String custState;
	private String custCity;
	private String custOccupation;
	private String address;
	private String autogeneratedPwd;
	private String userRole;
	
	

	public void setCustId(int custId) {
		this.custId = custId;
	}
	
	public int getCustId() {
		return custId;
	}

	public String getUserRole() {
		return userRole;
	}

	public void setUserRole(String userRole) {
		this.userRole = userRole;
	}

	public String getAutogeneratedPwd() {
		return autogeneratedPwd;
	}

	public void setAutogeneratedPwd(String autogeneratedPwd) {
		this.autogeneratedPwd = autogeneratedPwd;
	}

	public String getCustName() {
		return custName;
	}

	public void setCustName(String custName) {
		this.custName = custName;
	}

	public String getFrom() {
		return from;
	}

	public void setFrom(String from) {
		this.from = from;
	}

	

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getMiddleName() {
		return middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getCustMobNo() {
		return custMobNo;
	}

	public void setCustMobNo(String custMobNo) {
		this.custMobNo = custMobNo;
	}

	public String getGender() {
		return gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getCustNationlity() {
		return custNationlity;
	}

	public void setCustNationlity(String custNationlity) {
		this.custNationlity = custNationlity;
	}

	public String getCustDob() {
		return custDob;
	}

	public void setCustDob(String custDob) {
		this.custDob = custDob;
	}

	public String getCustPincode() {
		return custPincode;
	}

	public void setCustPincode(String custPincode) {
		this.custPincode = custPincode;
	}

	public String getCustCountry() {
		return custCountry;
	}

	public void setCustCountry(String custCountry) {
		this.custCountry = custCountry;
	}

	public String getCustState() {
		return custState;
	}

	public void setCustState(String custState) {
		this.custState = custState;
	}

	public String getCustCity() {
		return custCity;
	}

	public void setCustCity(String custCity) {
		this.custCity = custCity;
	}

	public String getCustOccupation() {
		return custOccupation;
	}

	public void setCustOccupation(String custOccupation) {
		this.custOccupation = custOccupation;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

}
