create table customersdata
(
custId number(9)primary key,
custName varchar(25),
middleName varchar(25),
lastName varchar(25),
email varchar(80),
custMobNo varchar(15),
gender varchar(25),
custNationlity varchar(25),
custDob varchar(25),
custPincode varchar(25),
custCountry varchar(25),
custState varchar(25),
custCity varchar(25),
custOccupation varchar(25),
address varchar(255),
autogeneratedPwd varchar(25),
userRole varchar(25)
);

insert into customersdata values(7,'deendayal','ddsa','kumawat','dd@gmail.com','9602063435','male','Indian','1-june-1993','332710','India','Rajasthan','Jaipur','Java Doveloper','Pune','ddsa','Employee');

create table employee123
(
empId number(9)primary key,
email varchar(80),
password varchar(20),
userRole varchar(50)
);
insert into employee123 values(1,'emp@gmail.com','emp','Employee');

create table owner123
(
userId number(9)primary key,
email varchar(80),
password varchar(20),
userRole varchar(50)
);
insert into owner123 values(1,'admin@gmail.com','admin','Admin');

create table employeedata
(
empId number(9)primary key,
empName varchar(25),
middleName varchar(25),
lastName varchar(25),
email varchar(80),
empMobNo varchar(15),
gender varchar(25),
empDesignation varchar(25),
empDob varchar(25),
empPincode varchar(25),
empCity varchar(25),
address varchar(25),
autogeneratedPwd varchar(25),
userRole varchar(25)
);
