package org.spring.EmployeeDaoImpl;

import java.sql.PreparedStatement;
import java.sql.SQLException;

import org.spring.EmployeeBeans.CustomersBeans;
import org.spring.EmployeeInterface.EmployeeDao;
import org.spring.UtilityClass.QueryOfDatabase;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.DataAccessException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.PreparedStatementCallback;
import org.springframework.stereotype.Repository;

@Repository
public class CustomerRegister implements EmployeeDao  {
	
	

		@Autowired(required = true)
		JdbcTemplate jdbcTemplate;
		
		public void setJdbcTemplate(JdbcTemplate jdbcTemplate) {
			this.jdbcTemplate = jdbcTemplate;
		}
		
		@Override
		public Boolean addCustomer(CustomersBeans customerbens) {
			
			
			return jdbcTemplate.execute(QueryOfDatabase.saveCustomers,new PreparedStatementCallback<Boolean>() {

				@Override
				public Boolean doInPreparedStatement(PreparedStatement pstmt) throws SQLException, DataAccessException {
					
					pstmt.setString(1, customerbens.getCustName());
					pstmt.setString(2, customerbens.getMiddleName());
					pstmt.setString(3, customerbens.getLastName());
					pstmt.setString(4, customerbens.getEmail());
					pstmt.setString(5, customerbens.getCustMobNo());
					pstmt.setString(6, customerbens.getGender());
					pstmt.setString(7, customerbens.getCustNationlity());
					//pstmt.setDate(8, new java.sql.Date(customerbens.getCustDob().getTime()));
					pstmt.setString(8, customerbens.getCustDob());
					pstmt.setString(9, customerbens.getCustPincode());
					pstmt.setString(10, customerbens.getCustCountry());
					pstmt.setString(11, customerbens.getCustState());
					pstmt.setString(12, customerbens.getCustCity());
					pstmt.setString(13, customerbens.getCustOccupation());
					pstmt.setString(14, customerbens.getAddress());
					pstmt.setString(15, customerbens.getAutogeneratedPwd());		
					return pstmt.execute();
					
					
				}
			});
			
		}

}
