package org.spring.AdminDaoImpl;

import java.sql.PreparedStatement;
import java.sql.SQLException;

import org.spring.AdminBeans.AdminChangePwdBeans;
import org.spring.AdminInterface.adminPwdChange;
import org.spring.UtilityClass.QueryOfDatabase;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.DataAccessException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.PreparedStatementCallback;
import org.springframework.stereotype.Repository;

@Repository
public class AdminPasswordChangeDao implements adminPwdChange {

	@Autowired (required = true)
	JdbcTemplate jdbcTemplate;
	
	public JdbcTemplate getJdbcTemplate() {
		return jdbcTemplate;
	}
	@Override
	public boolean adminPasswordChangeAndUpdates(AdminChangePwdBeans changePwdBeans) {
		System.out.println("HERE uSERiD IS \\\\\\\\\\\\\\\\"+changePwdBeans.getUserId());
		return jdbcTemplate.execute(QueryOfDatabase.adminChangePasswordUsingEmail,new PreparedStatementCallback<Boolean>() {

			@Override
			public Boolean doInPreparedStatement(PreparedStatement pstmt) throws SQLException, DataAccessException {
				
				pstmt.setInt(2, changePwdBeans.getUserId());
				pstmt.setString(1, changePwdBeans.getAutogeneratedPwd());
				
				return pstmt.execute();
			}
		});
		 
	}

}
