package org.spring.AdminDaoImpl;

import java.sql.PreparedStatement;
import java.sql.SQLException;

import org.spring.AdminBeans.EmployeeBeans;
import org.spring.AdminInterface.NewEmployeeInterface;
import org.spring.UtilityClass.QueryOfDatabase;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.DataAccessException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.PreparedStatementCallback;
import org.springframework.stereotype.Repository;

@Repository
public class DaoImplofEmployee implements NewEmployeeInterface {
	
	
	@Autowired(required = true)
	JdbcTemplate jdbcTemplate;
	
	public void setJdbcTemplate(JdbcTemplate jdbcTemplate) {
		this.jdbcTemplate = jdbcTemplate;
	}

	@Override
	public Boolean addNewEmployee(EmployeeBeans employeeBeans) {
		
		return jdbcTemplate.execute(QueryOfDatabase.addNewEmployeeData, new PreparedStatementCallback<Boolean>() {

			@Override
			public Boolean doInPreparedStatement(PreparedStatement pstmt) throws SQLException, DataAccessException {
				
				pstmt.setString(1, employeeBeans.getEmpName());
				pstmt.setString(2, employeeBeans.getMiddleName());
				pstmt.setString(3,employeeBeans.getLastName());
				pstmt.setString(4,employeeBeans.getEmail());
				pstmt.setString(5,employeeBeans.getEmpMobNo());
				pstmt.setString(6,employeeBeans.getGender());
				pstmt.setString(7,employeeBeans.getEmpDesignation());
				pstmt.setString(8,employeeBeans.getEmpDob());
				pstmt.setString(9,employeeBeans.getEmpPincode());
				pstmt.setString(10, employeeBeans.getEmpCity());
				pstmt.setString(11,employeeBeans.getAddress());
				pstmt.setString(12, employeeBeans.getAutogeneratedPwd());
				return pstmt.execute();
			}
		}); 
	}
	
	

}
