<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Admin Profile</title>
<link rel="stylesheet" href="assets/Bootstrap/css/bootstrap.min.css">
<link rel="stylesheet" href="assets/Bootstrap/css/bootstrap-select.css">

<script src="assets/Bootstrap/js/jquery.min.js"></script>
<script src="assets/Bootstrap/js/bootstrap.min.js"></script>
<script src="assets/Bootstrap/js/bootstrap-select.js"></script>

<script src="assets/validations/forgotPassword.js"></script>
<link rel="stylesheet" href="assets/css/form.css"/>

<!-- <script type="text/javascript">

</script> -->

<style type="text/css">
.glyphicon-ok{
color:green;
}
</style>
</head>
<body>

<%-- <h1>Your New Password is : ${MyPwd}</h1> --%>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="#">Welcome Admin</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
        <li class="dropdown">
         <a class="dropdown-toggle" data-toggle="dropdown" href="#">Menu <span class="caret"></span></a>
           <ul class="dropdown-menu">
            <li><a href="AddNewEmployees">Add New Employee</a></li>
            <li><a href="#">Page 1-2</a></li>
            <li><a href="#">Page 1-3</a></li>
          </ul>
        </li>
        <li class="dropdown">
         <a class="dropdown-toggle" data-toggle="dropdown" href="#">Profile <span class="caret"></span></a>
           <ul class="dropdown-menu">
            <li><a href="#">View Profile</a></li>
            <li><a onclick="document.getElementById('id02').style.display='block'" style="width:auto;">Change Password</a></li>
            <!-- <li><a href="#">Page 1-3</a></li> -->
          </ul>
        </li>
        <!-- <li><a href="new-contact.jsp">Create New Contact</a></li>
        <li><a href="view-Contact.action">View Contact</a></li> -->
      </ul>
      <ul class="nav navbar-nav navbar-right">
       <!--  <li><a href=""><span class="glyphicon glyphicon-user"></span> Change Password</a></li> -->
        <li><a href="logout.jsp"><span class="glyphicon glyphicon-log-in"></span> LogOut</a></li>
      </ul>
       
    </div>
  </div>
</nav>

<h1>${msg}</h1>

<h1>Welcome Admin</h1>
${adminsPassword.email}<br>
${adminsPassword.password}

 <!-- <span class="psw">Change <a  onclick="document.getElementById('id02').style.display='block'" style="width:auto;">password?</a></span> -->
<div id="id02" class="modal">
  
  <form class="modal-content animate" action="changeOwnPasswordByAdmin" name="myForm" method="post" onsubmit="return changePassword()">
    <div class="imgcontainer">
      <span onclick="document.getElementById('id02').style.display='none'" class="close" title="Close Modal">&times;</span>
      <img src="assets/images/img_avatar2.png" alt="Avatar" class="avatar">
    </div>

    <div class="container">
   
      <label><b>Email</b></label>
      <input type="text" placeholder="Enter Email" name="email" id="email">
      <span style="color: red; font-weight:bold; font-family: cursive;" id="emailError"></span>
      
      <label><b>New Password</b></label>
      <input type="password" placeholder="New Password" name="autogeneratedPwd" id="autogeneratedPwd">
      <span style="color: red; font-weight:bold; font-family: cursive;" id="newChangePasswordError"></span>
      
      <label><b>Confirm Password</b></label>
      <input type="password" placeholder="Confirm Password" id="confirmPwd" name="confirmPwd">
      <span style="color: red; font-weight:bold; font-family: cursive;" id="confirmPwdError"></span>

     
        
      <button type="submit">Submit</button>
     
    </div>

  </form>
</div>
<script>
// Get the modal
var modal = document.getElementById('id02');

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
    if (event.target == modal) {
        modal.style.display = "none";
    }
}
</script>
</body>
</html>