<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Login</title>


<script src="assets/validations/loginvalidations.js"></script>

<link rel="stylesheet" href="assets/css/form.css"/>

<!-- <script type="text/javascript">

</script> -->

<style>
.glyphicon-ok{
color:green;
}

</style>

</head>
<body>

<h2>Modal Login Form</h2>

<button onclick="document.getElementById('id01').style.display='block'" style="width:auto;">Login</button>

<div id="id01" class="modal">
  
  <form class="modal-content animate" action="roleLogin" method="get" name="myForm" onsubmit="return loginsValidations()">
    <div class="imgcontainer">
      <span onclick="document.getElementById('id01').style.display='none'" class="close" title="Close Modal">&times;</span>
      <img src="assets/images/img_avatar2.png" alt="Avatar" class="avatar">
    </div>

    <div class="container">
    <select name="userRole" id="userRole">
    		<option selected disabled>Select-Role</option>
    		<option>Admin</option>
    		<option>Employee</option>
    		<option>Customers</option>
    		<option>Visiters</option>
    </select>
    <br>
      <label><b>Email</b></label>
      <input type="text" placeholder="Enter Email" name="email" id="email_id">
		<span style="color: red; font-weight:bold;font-family: cursive;" id="emailError"></span><br>
     
      <label><b>Password</b></label>
      <input type="text" placeholder="Enter Password" name="autogeneratedPwd" id="autogeneratedPwd">
       <span style="color: red; font-weight:bold;font-family: cursive;" id="passwordError"></span>
        
      <button type="submit">Login</button>
      <input type="checkbox" checked="checked"> Remember me
    </div>

    <div class="container" style="background-color:#f1f1f1">
      <button type="button" onclick="document.getElementById('id01').style.display='none'" class="cancelbtn">Cancel</button>
     <span class="psw">Forgot <a href="#" onclick="document.getElementById('id02').style.display='block'" style="width:auto;">password?</a></span>
    <!--   <button onclick="document.getElementById('id02').style.display='block'" style="width:auto;">Forgot Password</button> -->
    </div>
  </form>
</div>

<div id="id02" class="modal">
  
  <form class="modal-content animate" action="forgotPasswordCheckedMail" method="get">
    <div class="imgcontainer">
      <span onclick="document.getElementById('id02').style.display='none'" class="close" title="Close Modal">&times;</span>
      <img src="assets/images/img_avatar2.png" alt="Avatar" class="avatar">
    </div>

    <div class="container">
   
      <label><b>Email</b></label>
      <input type="text" placeholder="Enter Email" name="email" required>

     
        
      <button type="submit">Submit</button>
     
    </div>

  </form>
</div>

<script>
// Get the modal
var modal = document.getElementById('id01');

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
    if (event.target == modal) {
        modal.style.display = "none";
    }
}

// Get the modal
var modal = document.getElementById('id02');

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
    if (event.target == modal) {
        modal.style.display = "none";
    }
}
</script>

</body>
</html>
