/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.70
 * Generated at: 2016-07-19 09:54:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" <header class=\"header\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <div class=\"col-12\">\r\n");
      out.write("                    <div class=\"col-4 mb-11 logo-set\">\r\n");
      out.write("                        <div class=\"logo\"><img src=\"image/blacklogo.png\" /></div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <nav class=\"mob-menu-icon mb-1\">\r\n");
      out.write("                        <span class=\"icon-bar\"></span>\r\n");
      out.write("                        <span class=\"icon-bar\"></span>\r\n");
      out.write("                       <span class=\"icon-bar\"></span>\r\n");
      out.write("                   </nav>\r\n");
      out.write("\r\n");
      out.write("                        \r\n");
      out.write("                    <nav class=\"col-8 menu mob-menu pull-right\">\r\n");
      out.write("                        \r\n");
      out.write("                         <nav class=\"mob-menu-icon\" style=\"padding: 26px 26px;width: 100%;box-sizing: border-box;border-bottom:2px solid #1565C0; \">\r\n");
      out.write("                        \r\n");
      out.write("                        <span class=\"icon-bar slide-icon-menu-color\"></span>\r\n");
      out.write("                        <span class=\"icon-bar slide-icon-menu-color\"></span>\r\n");
      out.write("                        <span class=\"icon-bar slide-icon-menu-color\"></span>\r\n");
      out.write("\r\n");
      out.write("                    </nav>\r\n");
      out.write("                       <!-- <div class=\"menu-item-box center \"><a href=\"#\" class=\"menu_link\">Home</a>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"sub_cata\" style=\"height: 200px;position: absolute;z-index: 99999;background-color: #000;margin-top: 29px;\">\r\n");
      out.write("                                Test sub cata\r\n");
      out.write("                            \r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </div>-->\r\n");
      out.write("                        <div class=\"menu-item-box center \"><a href=\"index.jsp\" class=\"menu-link\">Home</a></div>\r\n");
      out.write("                        <div class=\"menu-item-box center \"><a href=\"about_us.jsp\" class=\"menu-link\">About</a></div>\r\n");
      out.write("                        <div class=\"menu-item-box center \"><a href=\"service.jsp\" class=\"menu-link\">Services</a></div>\r\n");
      out.write("                        <div class=\"menu-item-box center \"><a href=\"#services\" class=\"menu-link\">Team</a></div>\r\n");
      out.write("                        <div class=\"menu-item-box center \"><a href=\"#portfolio\" class=\"menu-link\">Portfolio</a></div>\r\n");
      out.write("                        <div class=\"menu-item-box center \"><a href=\"#testimonial\" class=\"menu-link\">Testimonial</a></div>\r\n");
      out.write("                        <div class=\"menu-item-box center \"><a href=\"#contact\" class=\"menu-link\">Contact</a></div>\r\n");
      out.write("                        \r\n");
      out.write("\r\n");
      out.write("                        </nav>\r\n");
      out.write("                        \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                       \r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("            </header>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
